# This workflow will do a clean install of node dependencies, cache/restore them, build the backend API source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
       working-directory: ./apiserver

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: echo "export default {};" > src/config/ormconfig.ts
    - run: npm run build --if-present
#    - run: npm test
