# This workflow will do a clean install of node dependencies, cache/restore them, build the backend API source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
       working-directory: ./api

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2
    - name: Prepare Node ${{ matrix.node-version }} 🔧
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install 🔧
      run: npm ci
    - shell: bash
      run: curl --create-dirs -o root.crt -O https://cockroachlabs.cloud/clusters/f82eaea0-cfe2-4492-aa07-e986cd93e46d/cert
    - name: Build 🏗️
      run: npm run build --if-present
    - name: Test 🚨
      run: npm test
      env:
        PORT: ${{ secrets.PORT }}
        DB: ${{ secrets.DB }}
        DB_TYPE: ${{ secrets.DB_TYPE }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_CERT: ${{ secrets.DB_CERT }}
        AUTH0_ISSUER: ${{ secrets.AUTH0_ISSUER }}
        AUTH0_JWKS_URI: ${{ secrets.AUTH0_JWKS_URI }}
        AUTH0_TOKEN_URL: ${{ secrets.AUTH0_TOKEN_URL }}
        AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
        AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
        AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
