name: API - Deploy

on:
  push:
    branches: 
      - v1

jobs:   
  deploy:
    name: Deploy Staging on Heroku
    runs-on: ubuntu-latest
    env: 
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Prepare Node ${{ matrix.node-version }} 🔧
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install 🔧
        run: npm ci
      - name: Build 🏗️
        run: npm run build --if-present
      - name: Build and Push Image 🚨
        run: |
          heroku container:login 
          heroku container:push -a ${{ secrets.HEROKU_API_NAME }} web 
      - name: Release 🚀
        run: heroku container:release -a ${{ secrets.HEROKU_API_NAME }} web 