name: "Code Scanning"

on:
  push:
    branches:
      - main
      - v1
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "0 12 * * 0"

jobs:
  CodeQL:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Initialize CodeQL 🔧
        uses: github/codeql-action/init@v1
        with:
          languages: typescript
      - name: Autobuild 🏗️
        uses: github/codeql-action/autobuild@v1
      - name: Perform CodeQL Analysis 🚨
        uses: github/codeql-action/analyze@v1
